project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('katalog/', include('katalog.urls')),
    path('mywatchlist/', include('mywatchlist.urls')),
    path('todolist/', include('todolist.urls'))
]

# TODO: Implement Routings Here

todolist/urls.py
from django.urls import path
from .views import (delete_task_json, show_task_html, register, login_user, 
                    logout_user, create_task, update_task_status,
                    delete_task, get_json, show_json, create_task_ajax,
                    delete_task_json, update_task_status_json)

app_name = 'todolist'

urlpatterns = [
    path('', show_task_html, name='show_task_html'),
    path('json/', show_json, name='show_json'),
    path('json/get', get_json, name='get_json'),
    path('json/create-task', create_task_ajax, name='create_task_ajax'),
    path('json/update-status/<int:id>', update_task_status_json, name="update_status_json"),
    path('json/delete-task/<int:id>', delete_task_json, name="delete_task_json"),
    path('json/logout/', logout_user, name='logout_ajax'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('create-task/', create_task, name='create_task'),
    path('update-status/<int:id>', update_task_status, name="update_status"),
    path('delete-task/<int:id>', delete_task, name="delete_task"),
]

todolist/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Task(models.Model):
    FINISHED_STATUS = [
        (0, "Unfinished"),
        (1, "Finished")
    ]
    
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateField(auto_now="True")
    title = models.CharField(max_length=255)
    description = models.TextField()
    is_finished = models.IntegerField(default=0, choices=FINISHED_STATUS)
    
    
    

todolist/forms.py
from django import forms
from .models import Task

class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['title', 'description']
        error_messages = {
                'required' : 'This field is required'
        }
        title = forms.CharField(
                    label='Task Title', 
                    required=True,
                    max_length=255, 
                    widget=forms.TextInput(attrs={
                        'type': 'text',
                        'placeholder': 'Enter task title',
                    })
                )
        description = forms.CharField(
                    label='Task Description',
                    required=True,
                    widget=forms.Textarea(attrs={
                        'type': 'text',
                        'placeholder': 'Enter the task description',
                    }) 
                )   

todolist/views.py
from django.shortcuts import render
from .models import Task
from .forms import TaskForm
import datetime
from django.urls import reverse
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.core import serializers
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required(login_url='/todolist/login/')
def show_task_html(request):
    user_logged_in = request.user
    task_data = Task.objects.filter(user=user_logged_in).all()
    context = {
                'list_task': task_data,
                'name': 'Muhammad Rizqy Ramadhan',
                'NPM': '2106632182',
              }
    return render(request, "todolist.html", context)

@login_required(login_url='/todolist/login/')
def show_json(request):
    user_logged_in = request.user
    task_data = Task.objects.filter(user=user_logged_in).all()
    context = {
                'list_task': task_data,
                'name': 'Muhammad Rizqy Ramadhan',
                'NPM': '2106632182',
              }
    return render(request, "todolist_ajax.html", context)

@login_required(login_url='/todolist/login/')
def get_json(request):
    user = request.user
    task_data = Task.objects.all().filter(user = user)
    return HttpResponse(serializers.serialize("json", task_data), content_type="application/json")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
    if form.is_valid():
        form.save()
        messages.success(request, 'Account successfully created!')
        return redirect('todolist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user) # melakukan login terlebih dahulu
            response = HttpResponseRedirect(reverse("todolist:show_json")) # membuat response
            response.set_cookie('last_login', str(datetime.datetime.now())) # membuat cookie last_login dan menambahkannya ke dalam response
            return response
        else:
            messages.info(request, 'Incorrect Username or Password!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('todolist:login'))
    response.delete_cookie('last_login')
    return response

@login_required(login_url='/todolist/login/')
def create_task(request):
    if request.method == 'POST':
        title = request.POST.get('title')
        description = request.POST.get('description')
        user = request.user
        Task.objects.create(title=title, description=description, user=user)
        return HttpResponseRedirect(reverse("todolist:show_task_html"))
    # context = {} 
    # return render(request, 'create_task.html', context)
    
@login_required(login_url='/todolist/login/')
def create_task_ajax(request):
    if request.method == 'POST':
        title = request.POST.get('title')
        description = request.POST.get('description')
        user = request.user
        Task.objects.create(title=title, description=description, user=user)
        return HttpResponseRedirect(reverse("todolist:show_json"))

def update_task_status(request, id):
    task = Task.objects.get(id=id)
    if task: 
        if task.is_finished:
            task.is_finished = 0
            task.save()
            messages.success(request, "Oops, turned you have not finished the task!")
        else:
            task.is_finished = 1
            task.save()
            messages.success(request, "Yeay, you have finished the task!")
    else:
        messages.error(request, "Oops, the task can not be found")
    return HttpResponseRedirect(reverse("todolist:show_task_html"))

def update_task_status_json(request, id):
    task = Task.objects.get(id=id)
    if task: 
        if task.is_finished:
            task.is_finished = 0
            task.save()
            messages.success(request, "Oops, turned you have not finished the task!")
        else:
            task.is_finished = 1
            task.save()
            messages.success(request, "Yeay, you have finished the task!")
    else:
        messages.error(request, "Oops, the task can not be found")
    return HttpResponseRedirect(reverse("todolist:show_json"))

def delete_task(request, id):
    task = Task.objects.get(id=id)
    if task: 
        task.delete()
        messages.success(request, "Successfully deleted the task!")
    else:
        messages.error(request, "Oops, the task can not be found")
    return HttpResponseRedirect(reverse("todolist:show_task_html"))

def delete_task_json(request, id):
    task = Task.objects.get(id=id)
    if task: 
        task.delete()
        messages.success(request, "Successfully deleted the task!")
    else:
        messages.error(request, "Oops, the task can not be found")
    return HttpResponseRedirect(reverse("todolist:show_json"))
    
        

todolist/templates/create_task.html
{% extends 'base.html' %}
{% block meta %}
<title>Add New Task</title>
{% endblock meta %}

{% block content %}

<section class="vh-100 gradient-custom">
    <div class="container py-5 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12 col-md-8 col-lg-6 col-xl-5">
          <div class="card bg-dark text-white" style="border-radius: 1rem;">
            <div class="card-body p-5 text-center">
  
              <div class="mb-md-5 mt-md-4 pb-5">
  
                <h2 class="fw-bold mb-2 text-uppercase">Create Task</h2>
                <p class="text-white-50 mb-5">Please enter the title and description!</p>
                
                <form method="POST" action="">
                    {% csrf_token %}
                    <div class="form-outline form-white mb-4">
                    <input type="text" name="title" id="typeUsernameX" class="form-control form-control-lg" />
                    <label class="form-label" name="title" for="typeUsernameX">Title</label>
                    </div>
    
                    <div class="form-outline form-white mb-4">
                    <input type="text" name="description" id="typePasswordX" class="form-control form-control-lg" />
                    <label class="form-label" name="description" for="typePasswordX">Description</label>
                    </div>
    
                    <button class="btn btn-outline-light login_btn px-5" type="submit", value="Create">Create</button>
                </form>
  
              </div>
  
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

{% endblock content %}

todolist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}

<section class="vh-100 gradient-custom">
    <div class="container py-5 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12 col-md-8 col-lg-6 col-xl-5">
          <div class="card bg-dark text-white" style="border-radius: 1rem;">
            <div class="card-body p-5 text-center">
  
              <div class="mb-md-5 mt-md-4 pb-5">
  
                <h2 class="fw-bold mb-2 text-uppercase">Login</h2>
                <p class="text-white-50 mb-5">Please enter your login and password!</p>
                
                <form method="POST" action="">
                    {% csrf_token %}
                    <div class="form-outline form-white mb-4">
                    <input type="text" name="username" id="typeUsernameX" class="form-control form-control-lg" />
                    <label class="form-label" name="username" for="typeUsernameX">Username</label>
                    </div>
    
                    <div class="form-outline form-white mb-4">
                    <input type="password" name="password" id="typePasswordX" class="form-control form-control-lg" />
                    <label class="form-label" name="password" for="typePasswordX">Password</label>
                    </div>
    
                    <button class="btn btn-outline-light login_btn px-5" type="submit", value="Login">Login</button>
                </form>
  
              </div>
  
              <div>
                <p class="mb-0">Don't have an account? <a href="{% url 'todolist:register' %}">Sign Up</a>
                </p>
              </div>
  
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

{% endblock content %}

todolist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Account Registration</title>
{% endblock meta %}

{% block content %}  

<div class = "login">
    
    <section class="vh-100" style="background-color: #eee;">
        <div class="container h-100">
          <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-lg-12 col-xl-11">
              <div class="card text-black" style="border-radius: 25px;">
                <div class="card-body p-md-5">
                  <div class="row justify-content-center">
                    <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">
      
                      <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Sign up</p>
      
                      <form method="POST" action="">
                        {% csrf_token %}
                        <div class="d-flex flex-row align-items-center mb-4">
                          <i class="fas fa-user fa-lg me-3 fa-fw"></i>
                          <div class="form-outline flex-fill mb-0">
                            {{ form.as_table }}
                          </div>
                        </div>
      
                        <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                          <button type="submit" name="submit" class="btn btn-primary btn-lg">Register</button>
                        </div>
      
                      </form>
      
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
{% endblock content %}

todolist/templates/todolist.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title> TodoList </title>
<head>
    <link rel="stylesheet" href={% static 'todolist.css' %}>
</head>
{% endblock meta %}
{% block content %}
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
    <div class="container-fluid">
      <a class="navbar-brand" href="">WishList by {{ name }} - {{ NPM }}</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarMain" aria-controls="navbarMain" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>        
      <div class="collapse navbar-collapse" id="navbarMain">
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
            <button><a href="{% url 'todolist:create_task' %}">Add New Task</a></button>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Hello, {{user.get_username}}!
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="logout/">Logout</a></li>
          </li>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
</nav>
<br></br>
<div class="container">
    <div class="row">
      <div class="col">
        {% for task in list_task %}
        <div class="card">
            <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-green">
                <span class="badge badge-1"> {{ task.get_is_finished_display }}  </span>
              </span>
          <h3>{{task.title}}</h3>
          <small><i class="far fa-clock"></i> {{task.date}}</small>
          <p>{{task.description}}</p>
          <th>{{task.get_is_finished_display}} 
            <form action="{% url 'todolist:update_status' task.id %}" method="POST">
                {% csrf_token %}
                <button>Change Status</button>
            </form>
        </th>
        <th>
            <form action="{% url 'todolist:delete_task' task.id %}" method="POST">
                {% csrf_token %}
                <button>Delete Task</button>
            </form>
        </th>
        </div>
        <br></br>
        {% endfor %}
      </div>
    </div>
</div>

<div class="container-fluid">
    <p>Made with &#10084 by {{ name }} - {{ NPM }}</p>
</div>
{% endblock content %}
{% comment %} <h1>Assignment 4 and 5 PBP/PBD</h1>

<h3>Nama: {{name}}</h3>

<h3>NPM: {{NPM}}</h3>

<p>Welcome, {{user.get_username}}!</p>

<table>
    <tr>
    <th>Date Created</th>
    <th>Task Name</th>
    <th>Task Description</th>
    <th>Task Status</th>
    <th>Delete Task</th>

    </tr>
    {% for task in list_task %}
        <tr>
            <th>{{task.date}}</th>
            <th>{{task.title}}</th>
            <th>{{task.description}}</th>
            <th>{{task.get_is_finished_display}} 
                <form action="{% url 'todolist:update_status' task.id %}" method="POST">
                    {% csrf_token %}
                    <button>Change Status</button>
                </form>
            </th>
            <th>
                <form action="{% url 'todolist:delete_task' task.id %}" method="POST">
                    {% csrf_token %}
                    <button>Delete Task</button>
                </form>
            </th>
        </tr>
    {% endfor %}
</table>

<button><a href="{% url 'todolist:create_task' %}">Add New Task</a></button>
<button><a href="{% url 'todolist:logout' %}">Logout</a></button> 

{% if messages %}
<ul class="msg">
  {% for message in messages %}
  <li>{{ message }}</li>
  {% endfor %}
</ul>
{% endif %}
{% endcomment %}

todolist/templates/todolist_ajax.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title> TodoList </title>
<head>
    <link rel="stylesheet" href={% static 'todolist.css' %}>
</head>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
<script>
  function delete_task(pk) {
    $.ajax({
      url: "delete-task/" + pk,
      success: function() {
        
      }    
    });
  }
  function update_task(pk) {
    $.ajax({
      url: "update-status/" + pk,
      success: function() {
        
      }    
    });
  }
</script>
{% endblock meta %}
{% block content %}
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
    <div class="container-fluid">
      <a class="navbar-brand" href="">WishList by {{ name }} - {{ NPM }}</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarMain" aria-controls="navbarMain" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>        
      <div class="collapse navbar-collapse" id="navbarMain">
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
            <button><a href="{% url 'todolist:create_task' %}">Add New Task (Tugas 5)</a></button>
            <button class="btn btn-primary btn-lg" data-bs-toggle="modal" data-bs-target="#add_modal">
              Add Task (Tugas 6)
            </button>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Hello, {{user.get_username}}!
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="logout/">Logout</a></li>
          </li>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
</nav>
<br></br>
<div class="container" id="todolist_body">
    <div class="row">
      <div class="col" id="todolist_col">
        {% comment %} {% for task in list_task %} {% endcomment %}
        {% comment %} <div class="card"> {% endcomment %}
            {% comment %} <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-green">
                <span class="badge badge-1"> {{ task.get_is_finished_display }}  </span> {% endcomment %}
                <script type="text/javascript">
                  $.getJSON("{% url 'todolist:get_json' %}", function(data) {
                    if (data.length == 0) {
                      // If task is empty
                      var pesan = document.createElement('h2');
                      pesan.innerHTML = 'No Task Yet';
                      pesan.style.margin = "0px 10px";
                
                      $("#todolist_body").append(pesan);
                
                    }  
                    else {
                          $(data).each(function(key, value) {

                            var buttonRemove = document.createElement('button');
                            buttonRemove.classList.add('btn', 'btn-danger');
                            buttonRemove.style.marginRight = "10px";
                            buttonRemove.setAttribute('onclick', `delete_task(${value.pk})`);
                  
                            var link = document.createElement('a');
                            var linkText = document.createTextNode("Remove");
                            link.appendChild(linkText);
                            link.classList.add('link-light', 'text-decoration-none');
                            buttonRemove.appendChild(link)

                            var buttonUpdate = document.createElement('button');
                            buttonUpdate.classList.add('btn', 'btn-primary');
                            buttonUpdate.style.marginRight = "10px";
                            buttonUpdate.setAttribute('onclick', `update_task(${value.pk})`);
                  
                            var link = document.createElement('a');
                            var linkText = document.createTextNode("Update");
                            link.appendChild(linkText);
                            link.classList.add('link-light', 'text-decoration-none');
                  
                            buttonUpdate.appendChild(link);

                            if (value.fields.is_finished) {
                              $("#todolist_col").append($("<div class=\"card\">")
                                  .append($("<h3>").append(value.fields.title))
                                  .append($("<small>").append(value.fields.date))
                                  .append($("<p>").append(value.fields.description))
                                  .append($("<h5>").append("Finished"))
                                  .append($("<div>")
                                    .append(buttonUpdate))
                                  .append($("<div>")
                                    .append(buttonRemove))
                                  .append($("<br>")));
                            }
                             else {
                              $("#todolist_col").append($("<div class=\"card\">")
                                  .append($("<h3>").append(value.fields.title))
                                  .append($("<small>").append(value.fields.date))
                                  .append($("<p>").append(value.fields.description))
                                  .append($("<h5>").append("Not finished"))
                                  .append($("<div>")
                                  .append(buttonUpdate))
                                  .append($("<div>")
                                  .append(buttonRemove))
                                  .append($("<br>")));
                                  
                            };
                          })
                    }
                    })
              
                  .done(function(){
                      console.log("successfully loaded!");
                  })
              
                  .fail(function(e){
                      console.log('error:');
                      console.error(e);
                  });        
              </script>
              <br></br>
              </span>
          
          {% comment %} <h3>{{task.title}}</h3>
          <small><i class="far fa-clock"></i> {{task.date}}</small>
          <p>{{task.description}}</p> {% endcomment %}
          {% comment %} <th>{{task.get_is_finished_display}}  {% endcomment %}
            {% comment %} <th><form action="{% url 'todolist:update_status' task.id %}" method="POST">
                {% csrf_token %}
                <button>Change Status</button>
            </form>
        </th>
        <th>
            <form action="{% url 'todolist:delete_task' task.id %}" method="POST">
                {% csrf_token %}
                <button>Delete Task</button>
            </form>
        </th> {% endcomment %}
        {% comment %} </div> {% endcomment %}
        <br></br>
        {% comment %} {% endfor %} {% endcomment %}
      </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="add_modal" tabindex="-1" aria-labelledby="add_task_modal" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="add_task_modal_label">Add New Task w/ AJAX</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form id="add_task" method="POST" action="{% url 'todolist:create_task_ajax'%}">
          {% csrf_token %}
  
              <p>Title:</p>
              <input type="text" id="title" name="title" placeholder="Title" class="form-control"><br/>
                      
              <p>Description:</p>
              <textarea cols="100" id="description" rows="10" name="description" placeholder="Description" style="max-width: 100%;"></textarea><br/>
              
          <div style="margin: 10px auto;">
              <input class="btn btn-primary" type="submit" name="submit" value="Add">
          </div>

        </form>
      </div>
    </div>
  </div>
</div>

<div class="container-fluid">
    <p>Made with &#10084 by {{ name }} - {{ NPM }}</p>
</div>
{% endblock content %}
{% comment %} <h1>Assignment 4 and 5 PBP/PBD</h1>

<h3>Nama: {{name}}</h3>

<h3>NPM: {{NPM}}</h3>

<p>Welcome, {{user.get_username}}!</p>

<table>
    <tr>
    <th>Date Created</th>
    <th>Task Name</th>
    <th>Task Description</th>
    <th>Task Status</th>
    <th>Delete Task</th>

    </tr>
    {% for task in list_task %}
        <tr>
            <th>{{task.date}}</th>
            <th>{{task.title}}</th>
            <th>{{task.description}}</th>
            <th>{{task.get_is_finished_display}} 
                <form action="{% url 'todolist:update_status' task.id %}" method="POST">
                    {% csrf_token %}
                    <button>Change Status</button>
                </form>
            </th>
            <th>
                <form action="{% url 'todolist:delete_task' task.id %}" method="POST">
                    {% csrf_token %}
                    <button>Delete Task</button>
                </form>
            </th>
        </tr>
    {% endfor %}
</table>

<button><a href="{% url 'todolist:create_task' %}">Add New Task</a></button>
<button><a href="{% url 'todolist:logout' %}">Logout</a></button> 

{% if messages %}
<ul class="msg">
  {% for message in messages %}
  <li>{{ message }}</li>
  {% endfor %}
</ul>
{% endif %}
{% endcomment %}